package main

import "time"

// GameState represents the current state of the game
type GameState struct {
	PlayerID      string    `json:"player_id"`
	Money         float64   `json:"money"`
	InitialMoney  float64   `json:"initial_money"`
	Reputation    int       `json:"reputation"`
	Health        int       `json:"health"`        // 0-100
	Energy        int       `json:"energy"`        // 0-100
	CurrentDate   time.Time `json:"current_date"`
	Job           *Job      `json:"job,omitempty"`
	Apartment     *Apartment `json:"apartment,omitempty"`
	Stocks        []Stock   `json:"stocks"`
	Crypto        []Crypto  `json:"crypto"`
	Inventory     []Item    `json:"inventory"`
	History       []Event   `json:"history"`
	ActiveOffers  []Offer   `json:"active_offers"`
	JobOffers     []JobOffer `json:"job_offers"`
	ApartmentOffers []ApartmentOffer `json:"apartment_offers"`
	StockOffers   []StockOffer `json:"stock_offers"`
	StockHistory  []StockHistory `json:"stock_history"` // Historical stock price data
	Agreements    []Agreement `json:"agreements"` // Recurring agreements/subscriptions
	IsWorking     bool      `json:"is_working"`
	WorkStartTime time.Time `json:"work_start_time,omitempty"`
	WorkEndTime   time.Time `json:"work_end_time,omitempty"`
	LastSalaryDate time.Time `json:"last_salary_date,omitempty"`
	LastNightHealthLossDate time.Time `json:"last_night_health_loss_date,omitempty"` // Track when health was last lost at night
	// Hospital state
	IsInHospital  bool      `json:"is_in_hospital"`
	HospitalEntryTime time.Time `json:"hospital_entry_time,omitempty"`
	// Game over tracking
	NegativeMoneyStartDate time.Time `json:"negative_money_start_date,omitempty"` // When money first went negative
	GameOver              bool      `json:"game_over"`
	GameOverReason        string    `json:"game_over_reason,omitempty"`
	// Multiplayer/Invite system
	InviteCode            string    `json:"invite_code,omitempty"` // This player's invite code
	InvitedBy             string    `json:"invited_by,omitempty"`  // Player ID who invited this player
	IsFirstPlayer         bool      `json:"is_first_player"`       // True if this is the first player (no invite needed)
	CreatedAt     time.Time `json:"created_at"`
}

// Job represents a job the player can have
type Job struct {
	ID                string  `json:"id"`
	Title             string  `json:"title"`
	Salary            float64 `json:"salary"` // Monthly salary
	Description       string  `json:"description"`
	HoursPerDay       int     `json:"hours_per_day"`
	WorkType          string  `json:"work_type"` // "fixed_time" or "hourly"
	WorkStart         string  `json:"work_start,omitempty"` // For fixed_time: "09:00"
	WorkEnd           string  `json:"work_end,omitempty"`   // For fixed_time: "17:00"
	HealthLossPerHour float64 `json:"health_loss_per_hour"` // Health lost per hour of work (AI-determined)
	EnergyLossPerHour float64 `json:"energy_loss_per_hour"` // Energy lost per hour of work (AI-determined)
	IsTrickery        bool    `json:"is_trickery,omitempty"`
	Reason            string  `json:"reason,omitempty"`
}

// JobOffer represents a job offer generated by AI
type JobOffer struct {
	ID                string    `json:"id"`
	Type              string    `json:"type"` // "good" or "trickery"
	Title             string    `json:"title"`
	Description       string    `json:"description"`
	Salary            float64   `json:"salary"` // Monthly salary
	HoursPerDay       int       `json:"hours_per_day"`
	WorkType          string    `json:"work_type"` // "fixed_time" or "hourly"
	WorkStart         string    `json:"work_start,omitempty"` // For fixed_time: "09:00"
	WorkEnd           string    `json:"work_end,omitempty"`   // For fixed_time: "17:00"
	HealthLossPerHour float64   `json:"health_loss_per_hour"` // Health lost per hour of work (AI-determined)
	EnergyLossPerHour float64   `json:"energy_loss_per_hour"` // Energy lost per hour of work (AI-determined)
	UpfrontCost       float64   `json:"upfront_cost,omitempty"` // Upfront cost (training fees, etc.) for scam jobs
	ExpiresAt         time.Time `json:"expires_at"`
	IsTrickery        bool      `json:"is_trickery"`
	Reason            string    `json:"reason,omitempty"`
	HintShown         bool      `json:"hint_shown,omitempty"` // Track if hint was purchased
	Messages          []string  `json:"messages,omitempty"`   // Messages sent to this offer (for n8n integration)
}

// Stock represents a stock investment
type Stock struct {
	Symbol      string    `json:"symbol"`
	Shares      int       `json:"shares"`
	BuyPrice    float64   `json:"buy_price"`
	CurrentPrice float64  `json:"current_price"`
	BoughtAt    time.Time `json:"bought_at"`
}

// StockOffer represents a stock offer generated by AI
type StockOffer struct {
	ID              string    `json:"id"`
	Symbol          string    `json:"symbol"`
	CompanyName     string    `json:"company_name"`
	Description     string    `json:"description"`
	CurrentPrice    float64   `json:"current_price"`
	IsSafe          bool      `json:"is_safe"`          // Safe or unsafe stock
	FailureChance   float64   `json:"failure_chance"`   // 0-100% chance of failure/crash
	Reliability     string    `json:"reliability"`      // "high", "medium", "low"
	Reason          string    `json:"reason,omitempty"` // Why it's safe/unsafe
	HintShown       bool      `json:"hint_shown,omitempty"` // Track if hint was purchased
	ExpiresAt       time.Time `json:"expires_at"`
	Messages        []string  `json:"messages,omitempty"`   // Messages sent to this offer (for n8n integration)
}

// StockHistory represents historical stock price data
type StockHistory struct {
	Symbol      string    `json:"symbol"`
	Price       float64   `json:"price"`
	Date        time.Time `json:"date"`
	Event       string    `json:"event,omitempty"` // "buy", "sell", "crash", "surge"
}

// Agreement represents a recurring agreement/subscription from an offer
type Agreement struct {
	ID              string    `json:"id"`
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	RecurrenceType  string    `json:"recurrence_type"` // "daily", "weekly", "monthly"
	StartedAt       time.Time `json:"started_at"`
	LastProcessedAt time.Time `json:"last_processed_at"`
	// Stat effects applied periodically
	HealthChange    int       `json:"health_change,omitempty"`    // Per period
	EnergyChange    int       `json:"energy_change,omitempty"`    // Per period
	ReputationChange int      `json:"reputation_change,omitempty"` // Per period
	MoneyChange     float64   `json:"money_change,omitempty"`     // Per period (can be negative for subscriptions)
	IsTrickery      bool      `json:"is_trickery,omitempty"`
	Reason          string    `json:"reason,omitempty"`
	// For reciprocal agreements (when creator provides service to buyer)
	IsReciprocal    bool      `json:"is_reciprocal,omitempty"`    // True if this is a reciprocal agreement for the creator
	OtherPartyID    string    `json:"other_party_id,omitempty"`   // ID of the other party (buyer or creator)
	OriginalPrice   float64   `json:"original_price,omitempty"`   // Original price per period (for penalty calculation)
	Price           float64   `json:"price,omitempty"`            // Price per period (for display and offer creation)
}

// Crypto represents a cryptocurrency investment
type Crypto struct {
	Symbol    string  `json:"symbol"`
	Amount    float64 `json:"amount"`
	BuyPrice  float64 `json:"buy_price"`
	CurrentPrice float64 `json:"current_price"`
	BoughtAt  time.Time `json:"bought_at"`
}

// Item represents an item in inventory
type Item struct {
	ID              string    `json:"id"`
	Name            string    `json:"name"`
	BuyPrice        float64   `json:"buy_price"`
	MarketPrice     float64   `json:"market_price"`
	BoughtAt        time.Time `json:"bought_at"`
	// Stat effects (can be positive or negative)
	HealthChange    int       `json:"health_change,omitempty"`    // Per day or per use
	EnergyChange    int       `json:"energy_change,omitempty"`    // Per day or per use
	ReputationChange int      `json:"reputation_change,omitempty"` // Per day or per use
	MoneyChange     float64   `json:"money_change,omitempty"`     // Per day or per use
	EffectFrequency string    `json:"effect_frequency,omitempty"` // "daily", "weekly", "monthly", "on_use"
}

// Offer represents an AI-generated offer
type Offer struct {
	ID          string    `json:"id"`
	Type        string    `json:"type"` // "trickery", "good", "market", "other"
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Price       float64   `json:"price"`
	OriginalPrice float64 `json:"original_price,omitempty"`
	Discount    float64   `json:"discount,omitempty"`
	ExpiresAt   time.Time `json:"expires_at"`
	IsTrickery  bool      `json:"is_trickery"`
	Reason      string    `json:"reason,omitempty"`
	// Stat effects when offer is accepted
	HealthChange    int     `json:"health_change,omitempty"`    // Change in health (-100 to 100)
	EnergyChange    int     `json:"energy_change,omitempty"`    // Change in energy (-100 to 100)
	ReputationChange int    `json:"reputation_change,omitempty"` // Change in reputation
	MoneyChange     float64 `json:"money_change,omitempty"`     // Additional money change (beyond price)
	HintShown       bool    `json:"hint_shown,omitempty"`       // Track if hint was purchased for other offers
	IsRecurring     bool    `json:"is_recurring,omitempty"`     // If true, becomes an Agreement; if false, becomes an Item
	RecurrenceType  string  `json:"recurrence_type,omitempty"`  // "daily", "weekly", "monthly" for agreements
	CreatedBy       string  `json:"created_by,omitempty"`       // Player ID who created this offer (for player-created offers)
	Messages        []string `json:"messages,omitempty"`        // Messages sent to this offer (for n8n integration)
}

// Event represents a game event
type Event struct {
	ID        string    `json:"id"`
	Type      string    `json:"type"`
	Message   string    `json:"message"`
	Amount    float64   `json:"amount,omitempty"`
	Timestamp time.Time `json:"timestamp"`
}

// ActionRequest represents a player action
type ActionRequest struct {
	Action string                 `json:"action"`
	Data   map[string]interface{} `json:"data"`
}

// ChatMessage represents a chat message with AI agents
type ChatMessage struct {
	Agent   string `json:"agent"` // "trickery", "offers", "guide"
	Message string `json:"message"`
	Context string `json:"context,omitempty"`
}

// ChatResponse represents AI agent response
type ChatResponse struct {
	Agent     string      `json:"agent"`
	Message   string      `json:"message"`
	Questions []string    `json:"questions,omitempty"`
	Offer     *Offer      `json:"offer,omitempty"`      // If chat created an offer
	Agreement *Agreement  `json:"agreement,omitempty"`  // If chat created an agreement
	Item      *Item       `json:"item,omitempty"`       // If chat created an item listing
	Created   bool        `json:"created,omitempty"`    // True if something was created
}

// Apartment represents an apartment the player can rent
type Apartment struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Rent        float64 `json:"rent"`        // Monthly rent
	Description string  `json:"description"`
	HealthGain  int     `json:"health_gain"` // Health gained per hour in apartment
	EnergyGain  int     `json:"energy_gain"` // Energy gained per hour in apartment
	IsTrickery  bool    `json:"is_trickery,omitempty"`
	Reason      string  `json:"reason,omitempty"`
}

// ApartmentOffer represents an apartment offer generated by AI
type ApartmentOffer struct {
	ID          string    `json:"id"`
	Type        string    `json:"type"` // "good" or "trickery"
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Rent        float64   `json:"rent"`        // Monthly rent
	HealthGain  int       `json:"health_gain"` // Health gained per hour
	EnergyGain  int       `json:"energy_gain"` // Energy gained per hour
	ExpiresAt   time.Time `json:"expires_at"`
	IsTrickery  bool      `json:"is_trickery"`
	Reason      string    `json:"reason,omitempty"`
	HintShown   bool      `json:"hint_shown,omitempty"` // Track if hint was purchased
	Messages    []string  `json:"messages,omitempty"`   // Messages sent to this offer (for n8n integration)
}

